# Generated by Django 5.2.4 on 2025-08-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inven_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='Category',
            field=models.CharField(choices=[('Cloth diapers', 'Cloth diapers'), ('Disposable diapers', 'Disposable diapers'), ('Swim diapers', 'Swim diapers'), ('New born', 'New born'), ('Small (4-8 kg) diapers', 'Small (4-8 kg) diapers'), ('Pant Style diapers', 'Pant Style diapers'), ('Washable Diaper', 'Washable Diaper'), ('Xxl (14-25 kg) diapers', 'Xxl (14-25 kg) diapers')], max_length=200),
        ),
    ]
